### ISSUE TITLE
Newline in 389-exception name

### ISSUE THREAD

**Issue by wking** [spdx/license-list-data#10]
In 2.6 and the current master, [`389-exception` has a newline in the license name][1]:

       "name": "389 Directory Server\nException",

I'm not sure whether that's a tooling issue (with this repo) or a source-data issue (with spdx/license-list), so I'm filing the issue in this PR.  If it's a source-data issue, we can either update spdx/license-list, or update this tooling to replace newlines with a single space when reading in the source XLS/ODS.

[1]: https://github.com/spdx/license-list-data/blob/a06aa08876afc9acda46c8d58fee3ed144c85ff9/json/exceptions/389-exception.json#L4

**Comment by goneall** [comment]
This is an issue with the source data - there is a newline in the column containing the name.

**Comment by goneall** [comment]
This was resolved when we switched to the XML generated license data.  Closing the issue.
