### ISSUE TITLE
Incorrect XML/HTML for https://spdx.org/licenses/SISSL

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-data#11]
This has been reported on IRC by @mzeinstra
>  Just wanted to state that https://spdx.org/licenses/SISSL is giving an error: " error on line 242 at column 13: Opening and ending tag mismatch: p line 0 and div

With firefox I get:
```
XML Parsing Error: mismatched tag. Expected: </p>.
Location: https://spdx.org/licenses/SISSL
Line Number 302, Column 9:      </div>
--------^
```

**Comment by goneall** [comment]
I patched the website to fix this issue.  The same problem existed with the SISSL-1.2 file.  This should be fixed in source once we move to the license list based on the XML version.
