### ISSUE TITLE
Remove ‘list’ tag (synonym for v2.5)

### ISSUE THREAD

**Issue by wking** [spdx/license-list-data#12]
```
$ git log --oneline --decorate -1 list
3f2d188 (tag: v2.5, tag: list) Version 2.5 license list
```

One tag is probably fine ;).  Can we delete the `list` tag?

**Comment by goneall** [comment]
Yikes.  Note sure how that happened.  I wrote some code to automatically push to the github repo, but I didn't think I was using that.

Going to leave this open until I have a chance to investigate.

**Comment by goneall** [comment]
Decided this was human error - the synonym has been removed - closing issue

**Comment by wking** [comment]
> … the synonym has been removed…

Did you forget to push the removal?  GitHub thinks the `list` tag is still there: https://github.com/spdx/license-list-data/tree/list

I think you want to run:

```console
$ git push origin :list
```

where `origin` should be your remote name for spdx/license-list-data.

**Comment by goneall** [comment]
Oops - you are correct on forgetting to push the changes.  It should be fixed now.
