### ISSUE TITLE
Add user friendly permissions/limitations

### ISSUE THREAD

**Issue by sharpaper** [spdx/license-list-data#13]
It would be very nice if a user friendly version of "dos and don'ts" could be added to SPDX. I'm thinking a set of properties like GitHub "Permissions/Limitations" ([example](https://github.com/gogits/gogs/blob/master/LICENSE)) or [this other example](https://tldrlegal.com/license/mit-license).

**Comment by wking** [comment]
On Fri, Nov 10, 2017 at 10:47:56AM +0000, sharpaper wrote:
> It would be very nice if a user friendly version of "dos and don'ts"
> could be added to SPDX.

I don't think SPDX is in the business of having opinions about
licenses, although see spdx/spdx-spec#46 for some discussion about
aggregating third-party opinions.  And in that case, SPDX would be in
the business of picking which third parties to aggregate.  Maybe
that's a fuzzy line…

**Comment by sharpaper** [comment]
Hi @wking 

I think it would also be fine to link SPDX to another (reputable) source, if any such source exists. For example I don't know how much GitHub or TLDRlegal are reputable in this context, but a link like "spdx:mit <sameAs> tldrlegal:mit" (if any such link can be created) would be fine too.

**Comment by wking** [comment]
On Fri, Nov 10, 2017 at 11:36:16AM +0000, sharpaper wrote:
> I think it would also be fine to link SPDX to another (reputable) source…

Yup, that's what's going on in spdx/spdx-spec#46.  See especially [1]
and later.

[1]: https://github.com/spdx/spdx-spec/issues/46#issuecomment-339482692

**Comment by goneall** [comment]
@sharpaper Would it be OK with you to continue this thread in  spdx/spdx-spec#46 and close this issue? We could also open a separate issue for the spec to track.  I would like to keep issue in this repo specific to data issues.

**Comment by sharpaper** [comment]
@goneall It's OK to me, both threads seems to tackle the same issue. In general I just think it's good if SPDX can be linked to as many other datasets as possible, such that more info can be "discovered" about a license.

**Comment by goneall** [comment]
> I just think it's good if SPDX can be linked to as many other datasets as possible, such that more info can be "discovered" about a license.

Agree
