### ISSUE TITLE
3.0 non-website formats have no blank lines

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list-data#16]
I looked briefly at `rdf`, `template`, `text`, and `html` -- none seem to have blank lines, eg where one would expect a paragraph, in contrast with the website HTML, which is as expected.

This makes these formats less useful for any context in which humans might be expected to read the licenses.

**Comment by wking** [comment]
On Fri, Dec 29, 2017 at 11:01:49AM -0800, Mike Linksvayer wrote:
> I looked briefly at `rdf`, `template`, `text`, and `html` -- none
> seem to have blank lines, eg where one would expect a paragraph, in
> contrast with the website HTML, which is as expected.

It looks like they currently have one newline instead of two.  You can
hack around that with something like:

  $ curl -s https://raw.githubusercontent.com/spdx/license-list-data/master/json/details/GPL-2.0.json | jq -r .licenseText | sed 's/$/\n/'g

but I agree that having spdx/tools insert blank lines between blocks
would be better.

**Comment by mlinksva** [comment]
There are many places where a newline should immediately followed by a blank line (i.e., where `<br>` is used in source instead of `<p></p>`. Simply doubling up newlines is also not great for humans reading.

**Comment by goneall** [comment]
Adding issue to the SPDX tools to address: https://github.com/spdx/tools/issues/135

There must be library out that that translates HTML to pretty printed text that should be able to help.

I probably won't have time to look at this for a few weeks since I'm working on some automated test/deployment scripts.

**Comment by wking** [comment]
On Fri, Dec 29, 2017 at 07:26:42PM +0000, Mike Linksvayer wrote:
> Simply doubling up newlines is also not great for humans reading.

Agreed (hence “hack” [1] ;).

[1]: https://github.com/spdx/license-list-data/issues/16#issuecomment-354488377

**Comment by mlinksva** [comment]
This might be another issue, but in case it's just my inability to read: what is the spdx/tools command or commands used to generate the data files in this repo? It's not obvious to me from either repo's READMEs.

(I haven't written any Java in over 10 years but just might try my hand at https://github.com/spdx/tools/issues/135 if I knew how to run the tools.)

**Comment by goneall** [comment]
@mlinksva Happy to have any help on the tools :)

The actual commands are undergoing some changes as I am working on a continuous integration tools to generate the data files as well as more testing.  It is probably safer to just point you to the code and update the README's once the commands are stabilized.

The main entrypoint for the command is [LicenseRDFaGenerator.java](https://github.com/spdx/tools/blob/4c9054942fd8ba1fb691de8950aeeca3fdf4addf/src/org/spdx/tools/LicenseRDFAGenerator.java#L121)

The specific code of interest in the code that translates the license XML files into the license text.

The basic flow of the program is LicenseRDFaGenerator -> Translate XML to the license objects (including the license text) -> Translate the license into various output files (including the text and template files)

The code that translates the license XML into the license template text is [LicenseXmlHelper.getLicenseTemplate](https://github.com/spdx/tools/blob/4c9054942fd8ba1fb691de8950aeeca3fdf4addf/src/org/spdx/licensexml/LicenseXmlHelper.java#L498) and the code that translates the license XML into text is [LicenseXmlHelper.getLicenseText](https://github.com/spdx/tools/blob/4c9054942fd8ba1fb691de8950aeeca3fdf4addf/src/org/spdx/licensexml/LicenseXmlHelper.java#L523)

**Comment by goneall** [comment]
This should be resolved with the 3.1 release of the license list - closing the issue.
