### ISSUE TITLE
Deprecate referenceNumber?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-data#23]
The [docs for this][1]:

> - referenceNumber – Generated number

don't really shed light on the intended semantics.  Licenses already have a short identifier, and those IDs are stable.  `referenceNumber`, on the other hand, seems to be mutable:

```console
$ diff -u <(git cat-file -p v2.6:website/licenses.json | jq -S .) <(git cat-file -p v3.0:website/licenses.json | jq -S .)
--- /dev/fd/63  2018-01-09 14:29:53.634748153 -0800
+++ /dev/fd/62  2018-01-09 14:29:53.634748153 -0800
@@ -1,16 +1,28 @@
 {
-  "licenseListVersion": "2.6",
+  "licenseListVersion": "3.0",
   "licenses": [
     {
-      "detailsUrl": "http://spdx.org/licenses/Glide.json",
+      "detailsUrl": "http://spdx.org/licenses/0BSD.json",
       "isDeprecatedLicenseId": false,
       "isOsiApproved": false,
-      "licenseId": "Glide",
-      "name": "3dfx Glide License",
-      "reference": "./Glide.html",
+      "licenseId": "0BSD",
+      "name": "BSD Zero Clause License",
+      "reference": "./0BSD.html",
       "referenceNumber": "1",
…
```

In v2.6, `Glide` had `referenceNumber` 1.  In v3.0, `0BSD` has `referenceNumber` 1 (and `Glide` is 150).  I don't see a point to providing an unstable number with unclear semantics, and would like to warn consumers away from the property with a deprecation notice.  At some point, we can remove it completely (although I don't see a need to set a timeline on that, and would be ok keeping the property forever after we deprecate it).

[1]: https://github.com/spdx/license-list-data/blame/64cfe5d853f89c758d56de0e39e8b9e0ef8e780f/accessingLicenses.md#L110

**Comment by goneall** [comment]
Resolved with PR #71
