### ISSUE TITLE
Add the note how to request a new license in the readme

### ISSUE THREAD

**Issue by vmarkovtsev** [spdx/license-list-data#26]
As a new user, it was unclear to me how to request new licenses to be added. Thus I filed https://github.com/spdx/license-list-data/issues/25 and https://github.com/spdx/license-list-data/issues/24
The resolution was https://github.com/spdx/license-list-data/issues/25#issuecomment-364506753
It should be added to the readme.

**Comment by wking** [comment]
On Fri, Feb 09, 2018 at 10:01:37AM -0800, Vadim Markovtsev wrote:
> It should be added to the readme.

The README already has [1], but I think some of that content should be
pulled out into a CONTRIBUTING.md and made more specific.

[1]: https://github.com/spdx/license-list-data/blame/fbcc7b6bf8276d6fa60c13545eb7df675b8f313c/README.md#L26

**Comment by goneall** [comment]
I just created a pull request.  To reduce the possible overlap of information, I just created a contributing section and referenced the contributing document in the license-list-XML repo.

**Comment by goneall** [comment]
I believe all the comments for the PR has been addressed, so I merged.  I believe this is resolved, so closing the issue.
