### ISSUE TITLE
RDF: link "isDeprecatedLicenseId" with "licenseId"

### ISSUE THREAD

**Issue by wonkydonky** [spdx/license-list-data#28]
Some licenses have a field called "isDeprecatedLicenseId", for example "GPL-3.0". However, this doesn't link to the license that they were replace with. This seems to be documented in the rdfs:comment field, but a direct link would make it more machine readable and useful.

Would it possible to add this information? I hope my question is clear enough, otherwise feel free to ask for clarification.

**Comment by wking** [comment]
> However, this doesn't link to the license that they were replace with.

This is spdx/license-list-XML#392.

**Comment by goneall** [comment]
I'm closing this as it is already reported in the license-list-XML issues list.
