### ISSUE TITLE
"isFsfLibre"

### ISSUE THREAD

**Issue by wonkydonky** [spdx/license-list-data#29]
What does "isFsfLibre" mean? I can't find it in the [vocabulary](https://spdx.org/SPDX-specifications/spdx-version-1.2/rdf-terms) and it also seems used inconsistently. For example "GPL-2.0" has "isFsfLibre = false" and "GPL-2.0-only" doesn't have it at all.

**Comment by wking** [comment]
On Fri, Mar 02, 2018 at 07:51:32AM -0800, wonkydonky wrote:
> What does "isFsfLibre" mean?

It's pulled from [1] with the HTML-class → tag translation in [2], so
“libre” is set for the following FSF categories:

* Free licenses, compatible with the GNU GPL
* Free licenses, compatible with the FDL
* Free licenses, incompatible with the GNU GPL and FDL

It would be good for [3] to document the generated property.

> For example "GPL-2.0" has "isFsfLibre = false" and "GPL-2.0-only"
> doesn't have it at all.

This is spdx/tools#141, which may need porting to
spdx/LicenseListPublisher.

[1]: https://www.gnu.org/licenses/license-list.html
[2]: https://github.com/wking/fsf-api/blob/ee338b3624a260d90509e4b0dac53f926b1e29e6/pull.py#L21-L27
[3]: https://github.com/spdx/LicenseListPublisher

**Comment by goneall** [comment]
> This is spdx/tools#141, which may need porting to spdx/LicenseListPublisher.

Ported

> It would be good for [3] to document the generated property.

We should document this in the spec - There is a more general issue to document the listed license fields which would include the isFsfLibra field: https://github.com/spdx/spdx-spec/issues/46

**Comment by goneall** [comment]
Since the SPDX tools and license list publish has been updated and there is an existing issue for adding it to the spec, I'm closing this issue.
