### ISSUE TITLE
Duplicate "name" property

### ISSUE THREAD

**Issue by wonkydonky** [spdx/license-list-data#31]
In the RDF dump some licenses have a duplicate "name" property. Only a few of them have, such as `BSD-2-Clause`, so I guess this is a bug as there should be only one.

**Comment by goneall** [comment]
Can you provide an example?  I took a look at 2 of the licenses in the RDF NT format and didn't find a duplicate name property.

**Comment by goneall** [comment]
I just checked the bsd-2-clause and it looks like there is only one spdx:name property.  This are several name properties associated with a var tag, which is OK.

**Comment by goneall** [comment]
I'm not able to duplicate this issue - closing.
