### ISSUE TITLE
Line breaks in plain text

### ISSUE THREAD

**Issue by silverhook** [spdx/license-list-data#32]
Currently the `*.txt` files in the `text/` folder don’t word-wrap/line-break, which makes it very hard to read.

Since we deprecated the old PlainText https://github.com/spdx/license-list we should provide something useful to replace it.

E.g. [REUSE.software 2.0](https://reuse.software/practices/2.0/) best practices explicitly recommend using the PlainText license texts from the (old) SPDX license repo.

**Comment by wking** [comment]
> Currently the *.txt files in the text/ folder don’t word-wrap/line-break, which makes it very hard to read.

If this is “we should use a prettier HTML-to-text converter, that would be a [LicenseListPublisher][1] issue.  If this is “we should expose upstream's canonical text/plain as well as their canonical text/html”, that's a [license-list-XML][2] issue.  Is this one of those, or something else entirely?

[1]: https://github.com/spdx/LicenseListPublisher
[2]: https://github.com/spdx/license-list-XML

**Comment by wonkydonky** [comment]
I think he means something nicely formatted [like this](https://www.gnu.org/licenses/gpl-3.0.txt).

**Comment by silverhook** [comment]
@wonkydonky, in practical terms, yes.

@wking, from the organisational PoV, good question. I haven’t thought about it that way when I submitted the issue.

I’d say that if we at all can, we should expose the upstream’s canonical text/plain (perhaps also text/html) – so in the majority of cases, it would be probably be a license-list-XML issue.

There will inevitably be cases where we can’t and in that case we should at least provide easily readable versions of these ourselves – and in those cases it0d be a LicenseListPulblisher issue, as you say.

**Comment by goneall** [comment]
Even if we decide we need to maintain the upstream canonical text, having a better pretty printer for text which translates the break and paragraph tags from the input XML into line feeds should help substantially.  

I entered an issue for the LicenseListPublisher to track: https://github.com/spdx/LicenseListPublisher/issues/6

This will solve the linefeeds, but not the word wrap.   Word wrap should be handled by the editor or viewer IMHO.

**Comment by goneall** [comment]
Note that previously, the text stored in the  https://github.com/spdx/license-list repository was not an exact copy of the upstream text.  It actually contained some formatting hints adding some additional spaces and linefeeds that are not present in the upstream text.

Maintaining the upstream will be quite a challenge since there are different formats (e.g. pdf, HTML, text with DOS style linefeeds, text with Linux style linefeeds, different text encodings).  Sometimes it isn't easy to determine the authoritative upstream text if there are multiple formats present.

We have the URL references in the license to point to the original sites for those that want to reference the origin.

For the use case where people want a way to copy/paste text that matches the original per the SPDX [license matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines), I am thinking that the better text pretty printer solution may be a more practical "good enough" approach.

**Comment by silverhook** [comment]
@goneall Thank you, the two issues you opened seem to me to meet what I’m looking for. I think at least pretty-printing should be done. The word-wrap is of lesser importance, but still a very nice to have.

> Note that previously, the text stored in the https://github.com/spdx/license-list repository was not an exact copy of the upstream text. It actually contained some formatting hints adding some additional spaces and linefeeds that are not present in the upstream text.
> 
> Maintaining the upstream will be quite a challenge since there are different formats (e.g. pdf, HTML, text with DOS style linefeeds, text with Linux style linefeeds, different text encodings). Sometimes it isn't easy to determine the authoritative upstream text if there are multiple formats present.

I understand that and also think that as long as we make sure that the license text is actually right, it would be much easier to simply keep a quasi-canonical version for ourselves.

> We have the URL references in the license to point to the original sites for those that want to reference the origin.
>
> For the use case where people want a way to copy/paste text that matches the original per the SPDX license matching guidelines, I am thinking that the better text pretty printer solution may be a more practical "good enough" approach.

From my anecdotal experience people are doing this and based on REUSE.software best practices, I suspect this will only happen more often.

I agree that the URL references and providing the pretty-printed texts should be a “good enough” solution.

**Comment by goneall** [comment]
@silverhook I just updated the text files with word-wrapped versions.  I checked a hand full of the licenses and the word wrapping seems to work fine.  If you get a chance, please review and let me know if this resolves the issue.

**Comment by silverhook** [comment]
@goneall I took a glance at a handful of them in plain text and html form and the results looks good to me. Thanks for taking a stab at this :+1:

**Comment by wking** [comment]
There may be a bug in the generator for 31f52f1.  It looks like lots of the `html/*.html` files lost trailing `<br/>` (which is fine) and gained `<p>` for most lines (also fine) but not for the first line (which seems odd).  For example, here's [the first line of 0BSD with no `<p>`][1].  And here's [the 389-exception][2].  The pattern seems to hold for the remaining licenses.  Can we get `<p>` around those first lines?

[1]: https://github.com/spdx/license-list-data/commit/31f52f1d0af86948d0f79e35083296c624782084#diff-2cc0f8e31c14dc78dd0891af63552580R1
[2]: https://github.com/spdx/license-list-data/commit/31f52f1d0af86948d0f79e35083296c624782084#diff-b2a2002bc71bfe0b093b110dfdd8a92bR1

**Comment by goneall** [comment]
> There may be a bug in the generator for 31f52f1

I looked back at the recent comments for the LicenseListPublisher and could not find a commit that would cause this change in the generated HTML.

The most likely suspect is https://github.com/spdx/LicenseListPublisher/commit/c19264b83a4df954bd9cab22bbd5b5a5ba3bf7d6#diff-39cb0d38a411e75e807e805c927bb200

@wking Do you think this will cause any issues in the formatting?  If not, I'd like to punt this to the next license list release.  I would like some more time to find out what caused the issue before fixing.

**Comment by goneall** [comment]
Never did find the reason for the change, but I did improve the HTML format: https://github.com/spdx/LicenseListPublisher/pull/28

**Comment by goneall** [comment]
Just pushed an updated.  I noticed there are additional new-lines in the new HTML format.  This should not be an issue when rendered through a browser.

**Comment by wking** [comment]
On Fri, Apr 13, 2018 at 01:40:43PM +0000, goneall wrote:
> @wking Do you think this will cause any issues in the formatting?

My guess is that most browsers will handle this well enough, although
there might be an abnormal margin between the initial, untagged
paragraph and the following paragraphs.
