### ISSUE TITLE
Broken HTML pages

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-data#33]
See for instance https://spdx.org/licenses/CPL-1.0 
With chromium:
```
This page contains the following errors:
error on line 469 at column 22: Entity 'copy' not defined
Below is a rendering of the page up to the first error.
```
With Firefox:
```
XML Parsing Error: undefined entity
Location: https://spdx.org/licenses/CPL-1.0
Line Number 469, Column 16:            <p>&copy; 2018          SPDX Workgroup a Linux Foundation Project. All Rights Reserved.        </p>
---------------^
```

**Comment by wking** [comment]
On Thu, Apr 26, 2018 at 03:20:11PM +0000, goneall wrote:
> Switching to `&#169;` may solve the problem.

We already declare the XML as UTF-8:

  $ curl -s https://spdx.org/licenses/CPL-1.0 | head -n1
  <?xml version="1.0" encoding="utf-8"?>

so we can also just use a UTF-8 ©.  Personally, I think that's easier
to read than &#169;.

**Comment by goneall** [comment]
> so we can also just use a UTF-8 ©

I've run into problems in the past where the template files were edited in the wrong encoding format, so I think I'll keep the &169; even though it is less readable.

**Comment by goneall** [comment]
Resolved.  LicenseListGenerator updated with https://github.com/spdx/LicenseListPublisher/pull/29

Website has been updated and this repository has been updated with the newly generated (corrected) files.

**Comment by wking** [comment]
Should we tag a point release here?

**Comment by goneall** [comment]
> Should we tag a point release here?

Good question.  We haven't tagged releases in the past for changes that only impacted the formatting and did not include any changes from the upstream license-list-XML.

Perhaps we could define the release numbers to indicate changes in the license list data that does not include changes to the upstream license-list-XML.  e.g. X.YY.ZZ - the ZZ increments would indicate such changes.

**Comment by wking** [comment]
On Thu, Apr 26, 2018 at 06:34:29PM -0700, goneall wrote:
> Perhaps we could define the release numbers to indicate changes in
> the license list data that does not include changes to the upstream
> license-list-XML.  e.g. X.YY.ZZ - the ZZ increments would indicate
> such changes.

Yeah, I think patch-level releases [1] make sense for these publishing
bugs.  Without tagged releases, it will be harder to link source for
our published past versions (spdx/LicenseListPublisher#11).

[1]: https://semver.org/spec/v2.0.0.html

**Comment by goneall** [comment]
Created a PR #34 to document the versioning.  @wking let me know any suggestions.  Once we close on the documented process, I'll tag the release.
