### ISSUE TITLE
Automate incorporation on IOS

### ISSUE THREAD

**Issue by AntoineGermanos** [spdx/license-list-data#35]
Hi, I need some help in the automation incorporating Liscenes to IOS; to protect the device and surpassing the broadband “issues”

**Comment by AntoineGermanos** [comment]
Hi. Thank you for your concern. 
I woukd appreciate if you can help.
I am saving eveyin “working copy” and i gave muself an iURL, SsH keys and connected bi gitlab, github, etc... but i dont know how to use them, nor taking any advantage out of them. Can you pllz help me with this? Yhan you

**Comment by pombredanne** [comment]
@AntoineGermanos these are FOSS license texts. This is not something for iOS license protection. Closing this
