### ISSUE TITLE
Some users expect MIT to appear earlier than MIT-*

### ISSUE THREAD

**Issue by fossygirl** [spdx/license-list-data#36]
For libraries using data fetched from https://spdx.org/licenses/licenses.json the license ids appear to be sorted alphabetically. However the `MIT` entry is not first in the `MIT*` family of ids. It would just be handy if they were already sorted. Is this something it'd be possible to change the ordering of?

**Comment by goneall** [comment]
@fossygirl The current licenses.json file is not sorted.  I added an issue to the tool that generates the JSON file:  https://github.com/spdx/LicenseListPublisher/issues/36

We typically update the tools for the license generation around the releases of new versions for the license list.  Typically once a quarter.  Let me know if this timing works out, we can always deploy a new version of the tools earlier if needed.

**Comment by fossygirl** [comment]
@goneall I see there's been a couple merged issues for this. Is this issue resolved?

**Comment by goneall** [comment]
@fossygirl It is resolved in the tool that generates the license list data.  We still need to update the license-list-xml repo to use a new version of the tool.  I plan on finishing that up before the next release of the license list.  I'll update and close the issue once that is complete.

**Comment by fossygirl** [comment]
@goneall That's great, thanks so much for the update.

**Comment by goneall** [comment]
I just pushed a new tools update to the license list XML repo.  The JSON licenses should now be sorted by license ID (the same sort used by the spdx.org/licenses website).

Closing the issue as resolved.
