### ISSUE TITLE
isDeprecatedLicenseId incorrectly set to False in JSON data for a deprecated exception

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-data#39]
https://github.com/spdx/license-list-data/blob/76b71ab7bc787f68e4847c6fe83a81ca3c82c0ef/json/exceptions/Nokia-Qt-exception-1.1.json#L2 is marked as not depreacted... yet https://github.com/spdx/license-list-XML/blob/1deba8cec7760cf4ebd63a64a29729e1a33b30d9/src/exceptions/Nokia-Qt-exception-1.1.xml#L3 is deprecated alright

**Comment by goneall** [comment]
Resolved and deployed
