### ISSUE TITLE
Update "Request New License" links in templates

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-data#40]
The SPDX website is being updated to point to the license-list-XML repo's CONTRIBUTING file for all "Request New License" links. This is to ensure consistency for new SPDX participants re: how to request or contribute a new license. This is being tracked in spdx/license-list-XML#680.

The License List and Exception List HTML file templates in license-list-data should be updated to point to https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md. The applicable files can be found at:

https://github.com/spdx/license-list-data/search?q=%22Request+New+License%22&unscoped_q=%22Request+New+License%22

**Comment by swinslow** [comment]
I can take this one on, I just don't have the ability to assign this issue to myself  =)

**Comment by goneall** [comment]
This has now been resolved with the SPDX tools update and version 3.4 of the license list.
