### ISSUE TITLE
Proposal: Create a github.io pages that "previews" the SPDX license list website

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-data#41]
We can enable github.io pages for license-list-data which would display the license list in a very similar format to the [SPDX license list website](https://spdx.org/licenses/).  This would allow us to preview any changes prior to releasing to the official website.

This can be accomplished by copying the website folder to a docs folder and configuring this repository to enable github pages for the docs folder.  The [LicenseListPublisher](https://github.com/spdx/licenselistpublisher) would need to be updated to create this additional directory.

One issue is that the current website pages relies on some style sheets and other web assets which are only on the linux foundation server hosting the pages.  This could be resolved by having the LicenseListPublish add those files to the docs directory.

Another issue is that there may be confusion between the github.io pages and the official spdx.org/licenses site.  This may require some additional text to be added to the index.html page.

**Comment by goneall** [comment]
I did some experimenting on creating the github web pages.   I created a branch gh-pages and copied the HTML from the website directory as well as the screen.cs and sorttable.js files.  I also copies over some files from the linux foundation website (style sheets etc).

The web pages look pretty reasonable, but the breadcrumbs on the license pages do not work and the pages need some kind if indication that it is not the official web page.  I'm thinking of prefixing all the titles on all the pages with "PREVIEW - ".

To make this operational, we can update the Makefile in the license-list-XML repo to checkout the gh-pages branch, remove all the existing .html files, copy over the latest .html files from the website directory and search/replace text to fix up the breadcrumbs and titles.

@swinslow @jlovejoy Let me know if this approach sounds reasonable.

**Comment by jackrmomo** [comment]
a

**Comment by goneall** [comment]
This action looks like it could be used: https://github.com/marketplace/actions/deploy-to-github-pages

This action can do a find/replace but we need to be on the ghpages branch: https://github.com/marketplace/actions/find-and-replace

**Comment by goneall** [comment]
resolved with PR #73
