### ISSUE TITLE
Corrupted URLs in json/licenses.json: whitespace at the start and end of "seeAlso"

### ISSUE THREAD

**Issue by vlsi** [spdx/license-list-data#50]
For instance:

```
      "seeAlso": [
        "http://www.libpng.org/pub/png/src/libpng-LICENSE.txt\n         "
      ],
```

```
      "seeAlso": [
        "\nhttps://www.ohwr.org/project/licenses/wikis/cern-ohl-v1.1"
      ],
```

and so on

**Comment by goneall** [comment]
This seems to happen when there is a linefeed in the source XML.  The LicenseListPublisher should be filtering these out.

I added an issue against the tool: https://github.com/spdx/LicenseListPublisher/issues/49

**Comment by goneall** [comment]
The LicenseListPublisher was updated to ignore line feeds and has been deployed.  This issue should now be resolved.
