### ISSUE TITLE
MIT-CMU should be marked as FSF- and OSI-approved

### ISSUE THREAD

**Issue by eighthave** [spdx/license-list-data#53]
MIT-CMU is not currently marked OSI-approved or _isFsfLibre_. I think it should be:

* FSF lists two closely related variants as  X11 or Expat, search for "MIT license" in https://www.gnu.org/licenses/license-list.html
* X11 is considered free: https://directory.fsf.org/wiki/License:X11
* Expat is considered free: https://directory.fsf.org/wiki/License:Expat
* It is included in Debian, so it is DFSG-free: https://metadata.ftp-master.debian.org/changelogs//main/f/flite/flite_2.1-release-3_copyright
* Fedora considers it "functionally identical" to MIT: https://fedoraproject.org/wiki/Licensing:MIT#CMU_Style

**Comment by goneall** [comment]
@jlovejoy @swinslow Any thoughts on this issue?  In looking at the license text, there are some differences between X11 and MIT-CMU (e.g. the no advertise clause).  MIT and MIT-CMU do seem quite similar but to not technically match per the [License Matching Guidelines](https://spdx.org/spdx-license-list/matching-guidelines).

@eighthave We generally leave it up to the FSF to describe which licenses they consider FSF Free/Libre.  If a license on the FSF website is equivalent to another license on the SPDX license list per the [License Matching Guidelines](https://spdx.org/spdx-license-list/matching-guidelines), we will also mark those equivalent licenses as FSF Free/Libre as well.
I would suggest asking FSF to add the MIT-CMU to their license-list page declaring it as FSF-Free.

**Comment by swinslow** [comment]
@goneall I agree that under the SPDX license matching guidelines, MIT and MIT-CMU are considered to be two different licenses. Even if they use similar language and might operate similarly, SPDX categorizes them as two different licenses.

Given that, agree that we would look to OSI and FSF for their own judgements about how they would consider MIT-CMU. SPDX would not make that judgement, but would instead reflect it if they update their websites to specify that the MIT-CMU formulation satisfies their particular criteria.

**Comment by eighthave** [comment]
Makes sense to me.  I think it would be helpful for @uniqx and I to explain our context for this and #52.  @uniqx has recently done a bunch of work in F-Droid to make our license management system entirely based on SPDX.  We then delegate to SPDX for which licenses are free by using the FSF and OSI stamps in SPDX, since SPDX includes some licenses that are non-free, or at least not free enough for F-Droid.  That leaves out MIT-CMU and BSD-2-clause, which are clearly free.

One potential solution to our problem would be if SPDX included more marks of approval like DFSG (Debian Free Software Guidelines) and Fedora.  Then F-Droid would accept any license approved by FSF, OSI, DFSG, or Fedora.  I'm a Debian Developer, so I know the DFSG stuff well.  If any license is included in Debian, it is considered DFSG-approved (if not, it should be removed).  Non-free licenses can be found in packages in the "non-free" section of Debian, which is not considered officially part of Debian.  There has been a big push in Debian to make the _debian/copyright_ file both machine readible as well as completely documenting all the copyrights and licenses in a package.  So this could provide an automated source of info for SPDX to generate the "DFSG-free" data.

**Comment by goneall** [comment]
@eighthave Glad to see you're using the SPDX ID's for F-Droid :)  

> One potential solution to our problem would be if SPDX included more marks of approval like DFSG (Debian Free Software Guidelines) and Fedora.

I would agree - the more data that helps correlate the different license lists the better.  To implement this, we would need the following:

1. List of licenses which meet the criteria - this would likely originate with the organization supporting the list (e.g. Debian or Fedora).
2. Correlation of the license names used by the other organization to the SPDX license ID's.
3. Update to the SPDX specs with the definition of the new flags.
4. Machine readable format of the SPDX license ID's and values (similar to what @wking produced for the FSF flags)
5. Updates to the [LicenseListPublisher ](https://github.com/spdx/licenselistpublisher)to read the flags and produce the SPDX license list data files

I can help with the LicenseListPublisher.  We would need volunteers to help with 1-4.

If you would like to propose a solution, we should move this issue to the [LicenseList-XML](https://github.com/spdx/license-list-XML) issues list which is managed by the SPDX legal team.

BTW - the FsfLibre flag has three states:
- true - The FSF website declares the license as compatible with GPL
- false - The FSF website declares the license as incompatible with GPL
- null or no value - The license is not listed on the FSF website

You could use the "false" as your first level of compatibility and only check with the other lists if the value is not present.

**Comment by eighthave** [comment]
I found https://github.com/spdx/license-list-XML/issues/876#issuecomment-519524038 so I'll continue that discussion there.

As for using _false_ in the FsFLibre flag, nice hack, but F-Droid needs positive approval.  I'm closing this since I agree that SPDX should follow the exact data that FSF and OSI post, rather trying to guess.
