### ISSUE TITLE
Dead upstream link

### ISSUE THREAD

**Issue by MTecknology** [spdx/license-list-data#62]
I brushed across this. I wonder if there are others...

https://spdx.org/licenses/NOSL.html
-> http://bits.netizen.com.au/licenses/NOSL/nosl.txt (for-sale domain)

... I love what SPDX does, but I'm struggling to wrap my head around these repos. Hopefully this is good enough. :)

**Comment by goneall** [comment]
@MTecknology Thanks for reporting the link - there are quite a few dead links in the repo.

There is an issue to track this in the tool that generates the data: https://github.com/spdx/LicenseListPublisher/issues/60

There is also [summer of code project idea](https://wiki.spdx.org/view/GSOC/GSOC_ProjectIdeas#Validate_License_Cross-References) targeted at resolving this - we have a few good proposals coming in on this and hope to have a solution in the fall.

I'm closing this issue as it is covered by the tools and project ideas.
