### ISSUE TITLE
.txt files with simple replacements.

### ISSUE THREAD

**Issue by julianstirling** [spdx/license-list-data#64]
The SPDX is a wonderful source for information on licences. I would really like to use it in [GitBuilding](gitbuilding.io) to auto generate licence text for projects.

Unfortunately  `spdx-tools-python` doesn't seem to have a way to generate licence text, and `spdx` is java. I really hope I haven't missed something obvious!

The text folder in this repo is almost everything I would need. However some licences require additional details like the author names and, or the year. In general this is in the form <year> or <copyright holder>.

The issue is that there is little consistency as the text comes from different sources. sometimes `<year>` is used in the main text (i.e. GPL v3). `<>` is also often used for around websites and email addresses. Some times `<copyright holder>` is `<copyright holders>`, `<COPYRIGHT HOLDERS>`, `<owner>`, or `<name of author>`.

I believe that all the meta information to accurately replace the correct information is already in the licence list XML. It would be great if a set of .txt files could be generated with any text that needs replacing being marked with consistent IDs that wont be found in other parts of the text. Perhaps:
`{{SPDX-REPLACE-YEAR}}`
and
`{{SPDX-REPLACE-COPYRIGHT-HOLDERS}}`

This way tools can use a simple find and replace to create licence complete licence files without the overhead of parsing the full-fat XML or the license template in these [.json files](https://spdx.org/licenses/0BSD.json)

Sorry if this issue should be in one of the other SPDX repos.

**Comment by julianstirling** [comment]
So having looked deeper I have found the templates folder which marks up a number of things. Using the syntax:
`<<var;name="NAME";original="ORIGINAL";match="MATCH">>`
i.e.
`<<var;name="copyrightHolderAsIs";original="Berkeley Software Design, Inc.";match=".+">>`

Are the exact meanings of the fields variable names i.e. "copyrightHolderAsIs" listed anywhere?

**Comment by goneall** [comment]
@julianstirling There is no definitions for the field names in the `var` fields.  The template language is specified at in the [SPDX Spec Appendix II](https://spdx.github.io/spdx-spec/appendix-II-license-matching-guidelines-and-templates/#spdx-license-list-template-access).  The only requirement is the name be unique within the template file.

**Comment by julianstirling** [comment]
Thanks @goneall, I think bouncing between GitHub readmes and other technical files I somewhat missed the point of the licence list. I interpreted it to be a list of licences for projects to choose from and hence the templates being a way to produce the fully formed licence file; rather than templates to match licence files with.

Sorry if this is out of scope. I have looked at choosealicence.com but unlike SPDX they don't have Hardware licences which is the main focus of the work I am doing.

**Comment by goneall** [comment]
@julianstirling No worries.  We would certainly support using the license list as a way to choose a license - anything to prevent open source license proliferation is a good thing :)  You are correct, however, in that the templates really only help with the matching and not license construction.

The SPDX community is pretty open to additional use cases and enhancing the spec if there is enough volunteers to implement the changes.  If you want to make any proposals, the best place would be the issues on the [license list XML repo](https://github.com/spdx/license-list-XML).

I'll go ahead and close this issue.
