### ISSUE TITLE
Markdown license

### ISSUE THREAD

**Issue by TheTechRobo** [spdx/license-list-data#65]
I was going to add the [DBAD license](https://github.com/thetechrobo/dbad) but it is a markdown license and I can't find a folder for markdown.

Is it OK? Thanks! :)

**Comment by goneall** [comment]
@TheTechRobo To get a license in the license list data - submit a request to the SPDX team.  See: https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md#request-a-new-license-or-exception-be-added-to-the-spdx-license-list
