### ISSUE TITLE
RDF dump

### ISSUE THREAD

**Issue by insanecorgi** [spdx/license-list-data#7]
Is there an RDF dump of SPDX? The best I could find is the RDFa folder in this repository containing only .html files. Would it be possible to create a dump in one of these format: rdf/xml, nt, turtle?

Thank you.

**Comment by goneall** [comment]
I’ll put this on the todo list for the tool that generates these files.

**Comment by insanecorgi** [comment]
> I’ll put this on the todo list for the tool that generates these files.

Thank you. Where/how can check when they are available?

**Comment by goneall** [comment]
I’ll post back to this issue when it is available.  I will plan on the next release of the license list for availability.

**Comment by goneall** [comment]
The tool that generates the files has been updated.  license-list-data has been updated with the new formats and the readme file has been updated.
