### ISSUE TITLE
Link (License) with (LicenseException)

### ISSUE THREAD

**Issue by mongoponzo** [spdx/license-list-data#8]
I looked at the data but I don't see a connection between licenses and their exception. For example there is `MIT` and `MIT-advertising`, but they are treated as separate licenses. There doesn't seem to be a link such as `MIT --> has exception --> MIT-advertising`.

Or am I wrong?

**Comment by mongoponzo** [comment]
mmmm maybe I don't fully understand what "LicenseException" are? Looks like `MIT-advertising` is treated as a license and not as an exception.

**Comment by kemitchell** [comment]
SPDX isn't clear about when extra language bolted onto an existing license becomes an "exception", versus a new license, identified as a whole. That's come up again just recently on the mailing list, for a BSD-2-Clause plus patent license out of Intel.

As a practical matter, almost nobody uses `MIT-advertising`.  Probably not worth chasing.

**Comment by goneall** [comment]
In this case, the ```MIT-advertising``` is a license and not used as an exception.

You can determine if a JSON file references a license or exception by the property/tag name used to represent the text.  ```licenseText``` is used for a license and ```exceptionText``` is used for exceptions.  They are also stored in separate directories and have separate table of content JSON files.

As @kemitchell mentioned, there is a fuzzy line between adding an exception to an existing license or creating a new license.  These are discussed on the spdx legal email distribution list.

Closing this as an issue on the data - if you feel this should be changed to an exception, pls. send an email to spdx-legal@lists.spdx.org.
