### ISSUE TITLE
Incorrect "see also" data

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-data#9]
Two licenses have a list of "See also" data with "none" and "found" which is likely some artifact of data conversion ... See 
- https://github.com/spdx/license-list-data/blob/44eb7cb14a102a092780e6864b6e1c52c3ebcf28/json/details/GPL-2.0-with-bison-exception.json#L9
- https://github.com/spdx/license-list-data/blob/44eb7cb14a102a092780e6864b6e1c52c3ebcf28/json/details/GPL-2.0-with-GCC-exception.json#L9 
```
"seeAlso": [
    "none",
    "found"
],
```

**Comment by goneall** [comment]
This is due to the spreadsheet having a value of "none found" in the column for additional URL's.  This will be fixed when we convert to the license-list-XML format.

**Comment by goneall** [comment]
I just verified that this has now been resolved.  Closing the issue.
